// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_model_data
SEXP make_model_data(List x);
RcppExport SEXP _idmEstimation_make_model_data(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_model_data(x));
    return rcpp_result_gen;
END_RCPP
}
// em_fit
Rcpp::List em_fit(SEXP md_ptr, Rcpp::Nullable<Rcpp::NumericVector> z_init, Rcpp::Nullable<Rcpp::NumericVector> lambda_init, int max_iter, double tol, bool verbose);
RcppExport SEXP _idmEstimation_em_fit(SEXP md_ptrSEXP, SEXP z_initSEXP, SEXP lambda_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr(md_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(em_fit(md_ptr, z_init, lambda_init, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_idmEstimation_make_model_data", (DL_FUNC) &_idmEstimation_make_model_data, 1},
    {"_idmEstimation_em_fit", (DL_FUNC) &_idmEstimation_em_fit, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_idmEstimation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
