// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_penalty_config
SEXP create_penalty_config(List penalty_data);
RcppExport SEXP _idmEstimation_create_penalty_config(SEXP penalty_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type penalty_data(penalty_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(create_penalty_config(penalty_data));
    return rcpp_result_gen;
END_RCPP
}
// create_full_data
SEXP create_full_data(List data);
RcppExport SEXP _idmEstimation_create_full_data(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(create_full_data(data));
    return rcpp_result_gen;
END_RCPP
}
// calc_log_likelihood
double calc_log_likelihood(SEXP full_data_ptr, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23);
RcppExport SEXP _idmEstimation_calc_log_likelihood(SEXP full_data_ptrSEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type full_data_ptr(full_data_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_log_likelihood(full_data_ptr, theta_12, theta_13, theta_23));
    return rcpp_result_gen;
END_RCPP
}
// calc_full_penalty
double calc_full_penalty(SEXP full_data_ptr, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23, double kappa_12, double kappa_13, double kappa_23);
RcppExport SEXP _idmEstimation_calc_full_penalty(SEXP full_data_ptrSEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP, SEXP kappa_12SEXP, SEXP kappa_13SEXP, SEXP kappa_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type full_data_ptr(full_data_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_12(kappa_12SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_13(kappa_13SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_23(kappa_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_full_penalty(full_data_ptr, theta_12, theta_13, theta_23, kappa_12, kappa_13, kappa_23));
    return rcpp_result_gen;
END_RCPP
}
// calc_penalized_log_likelihood
List calc_penalized_log_likelihood(SEXP full_data_ptr, SEXP penalty_config_ptr, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23, double kappa_12, double kappa_13, double kappa_23);
RcppExport SEXP _idmEstimation_calc_penalized_log_likelihood(SEXP full_data_ptrSEXP, SEXP penalty_config_ptrSEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP, SEXP kappa_12SEXP, SEXP kappa_13SEXP, SEXP kappa_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type full_data_ptr(full_data_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type penalty_config_ptr(penalty_config_ptrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_12(kappa_12SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_13(kappa_13SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_23(kappa_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_penalized_log_likelihood(full_data_ptr, penalty_config_ptr, theta_12, theta_13, theta_23, kappa_12, kappa_13, kappa_23));
    return rcpp_result_gen;
END_RCPP
}
// make_model_data
SEXP make_model_data(List x);
RcppExport SEXP _idmEstimation_make_model_data(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_model_data(x));
    return rcpp_result_gen;
END_RCPP
}
// em_fit
Rcpp::List em_fit(SEXP md_ptr, Rcpp::Nullable<Rcpp::NumericVector> z_init, Rcpp::Nullable<Rcpp::NumericVector> lambda_init, int max_iter, double tol, bool verbose, bool eval_likelihood, bool use_true_EM);
RcppExport SEXP _idmEstimation_em_fit(SEXP md_ptrSEXP, SEXP z_initSEXP, SEXP lambda_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP, SEXP eval_likelihoodSEXP, SEXP use_true_EMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr(md_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type eval_likelihood(eval_likelihoodSEXP);
    Rcpp::traits::input_parameter< bool >::type use_true_EM(use_true_EMSEXP);
    rcpp_result_gen = Rcpp::wrap(em_fit(md_ptr, z_init, lambda_init, max_iter, tol, verbose, eval_likelihood, use_true_EM));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_idmEstimation_create_penalty_config", (DL_FUNC) &_idmEstimation_create_penalty_config, 1},
    {"_idmEstimation_create_full_data", (DL_FUNC) &_idmEstimation_create_full_data, 1},
    {"_idmEstimation_calc_log_likelihood", (DL_FUNC) &_idmEstimation_calc_log_likelihood, 4},
    {"_idmEstimation_calc_full_penalty", (DL_FUNC) &_idmEstimation_calc_full_penalty, 7},
    {"_idmEstimation_calc_penalized_log_likelihood", (DL_FUNC) &_idmEstimation_calc_penalized_log_likelihood, 8},
    {"_idmEstimation_make_model_data", (DL_FUNC) &_idmEstimation_make_model_data, 1},
    {"_idmEstimation_em_fit", (DL_FUNC) &_idmEstimation_em_fit, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_idmEstimation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
