// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_model_data
SEXP make_model_data(List x);
RcppExport SEXP _idmEstimation_make_model_data(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_model_data(x));
    return rcpp_result_gen;
END_RCPP
}
// em_fit
Rcpp::List em_fit(SEXP md_ptr, Rcpp::Nullable<Rcpp::NumericVector> z_init, Rcpp::Nullable<Rcpp::NumericVector> lambda_init, int max_iter, double tol, bool verbose);
RcppExport SEXP _idmEstimation_em_fit(SEXP md_ptrSEXP, SEXP z_initSEXP, SEXP lambda_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr(md_ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type z_init(z_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(em_fit(md_ptr, z_init, lambda_init, max_iter, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// create_penlik_model_data
SEXP create_penlik_model_data(List x);
RcppExport SEXP _idmEstimation_create_penlik_model_data(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(create_penlik_model_data(x));
    return rcpp_result_gen;
END_RCPP
}
// calc_case_1_log_likelihood
double calc_case_1_log_likelihood(SEXP md_ptr_case_1, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23);
RcppExport SEXP _idmEstimation_calc_case_1_log_likelihood(SEXP md_ptr_case_1SEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_1(md_ptr_case_1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_case_1_log_likelihood(md_ptr_case_1, theta_12, theta_13, theta_23));
    return rcpp_result_gen;
END_RCPP
}
// calc_case_2_log_likelihood
double calc_case_2_log_likelihood(SEXP md_ptr_case_2, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23);
RcppExport SEXP _idmEstimation_calc_case_2_log_likelihood(SEXP md_ptr_case_2SEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_2(md_ptr_case_2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_case_2_log_likelihood(md_ptr_case_2, theta_12, theta_13, theta_23));
    return rcpp_result_gen;
END_RCPP
}
// calc_case_3_log_likelihood
double calc_case_3_log_likelihood(SEXP md_ptr_case_3, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23);
RcppExport SEXP _idmEstimation_calc_case_3_log_likelihood(SEXP md_ptr_case_3SEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_3(md_ptr_case_3SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_case_3_log_likelihood(md_ptr_case_3, theta_12, theta_13, theta_23));
    return rcpp_result_gen;
END_RCPP
}
// calc_case_4_log_likelihood
double calc_case_4_log_likelihood(SEXP md_ptr_case_4, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23);
RcppExport SEXP _idmEstimation_calc_case_4_log_likelihood(SEXP md_ptr_case_4SEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_4(md_ptr_case_4SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_case_4_log_likelihood(md_ptr_case_4, theta_12, theta_13, theta_23));
    return rcpp_result_gen;
END_RCPP
}
// calc_penlik_log_likelihood
double calc_penlik_log_likelihood(SEXP md_ptr_case_1, SEXP md_ptr_case_2, SEXP md_ptr_case_3, SEXP md_ptr_case_4, const arma::vec& theta_12, const arma::vec& theta_13, const arma::vec& theta_23);
RcppExport SEXP _idmEstimation_calc_penlik_log_likelihood(SEXP md_ptr_case_1SEXP, SEXP md_ptr_case_2SEXP, SEXP md_ptr_case_3SEXP, SEXP md_ptr_case_4SEXP, SEXP theta_12SEXP, SEXP theta_13SEXP, SEXP theta_23SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_1(md_ptr_case_1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_2(md_ptr_case_2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_3(md_ptr_case_3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_4(md_ptr_case_4SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12(theta_12SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13(theta_13SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23(theta_23SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_penlik_log_likelihood(md_ptr_case_1, md_ptr_case_2, md_ptr_case_3, md_ptr_case_4, theta_12, theta_13, theta_23));
    return rcpp_result_gen;
END_RCPP
}
// optimize_penlik
List optimize_penlik(SEXP md_ptr_case_1, SEXP md_ptr_case_2, SEXP md_ptr_case_3, SEXP md_ptr_case_4, const arma::vec& theta_12_init, const arma::vec& theta_13_init, const arma::vec& theta_23_init, int max_iter, double epsilon);
RcppExport SEXP _idmEstimation_optimize_penlik(SEXP md_ptr_case_1SEXP, SEXP md_ptr_case_2SEXP, SEXP md_ptr_case_3SEXP, SEXP md_ptr_case_4SEXP, SEXP theta_12_initSEXP, SEXP theta_13_initSEXP, SEXP theta_23_initSEXP, SEXP max_iterSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_1(md_ptr_case_1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_2(md_ptr_case_2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_3(md_ptr_case_3SEXP);
    Rcpp::traits::input_parameter< SEXP >::type md_ptr_case_4(md_ptr_case_4SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_12_init(theta_12_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_13_init(theta_13_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_23_init(theta_23_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_penlik(md_ptr_case_1, md_ptr_case_2, md_ptr_case_3, md_ptr_case_4, theta_12_init, theta_13_init, theta_23_init, max_iter, epsilon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_idmEstimation_make_model_data", (DL_FUNC) &_idmEstimation_make_model_data, 1},
    {"_idmEstimation_em_fit", (DL_FUNC) &_idmEstimation_em_fit, 6},
    {"_idmEstimation_create_penlik_model_data", (DL_FUNC) &_idmEstimation_create_penlik_model_data, 1},
    {"_idmEstimation_calc_case_1_log_likelihood", (DL_FUNC) &_idmEstimation_calc_case_1_log_likelihood, 4},
    {"_idmEstimation_calc_case_2_log_likelihood", (DL_FUNC) &_idmEstimation_calc_case_2_log_likelihood, 4},
    {"_idmEstimation_calc_case_3_log_likelihood", (DL_FUNC) &_idmEstimation_calc_case_3_log_likelihood, 4},
    {"_idmEstimation_calc_case_4_log_likelihood", (DL_FUNC) &_idmEstimation_calc_case_4_log_likelihood, 4},
    {"_idmEstimation_calc_penlik_log_likelihood", (DL_FUNC) &_idmEstimation_calc_penlik_log_likelihood, 7},
    {"_idmEstimation_optimize_penlik", (DL_FUNC) &_idmEstimation_optimize_penlik, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_idmEstimation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
