# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_model_data <- function(x) {
    .Call(`_idmEstimation_make_model_data`, x)
}

em_fit <- function(md_ptr, z_init = NULL, lambda_init = NULL, max_iter = 100L, tol = 1e-3, verbose = TRUE) {
    .Call(`_idmEstimation_em_fit`, md_ptr, z_init, lambda_init, max_iter, tol, verbose)
}

create_penlik_model_data <- function(data) {
    .Call(`_idmEstimation_create_penlik_model_data`, data)
}

calc_log_likelihood <- function(md_ptr, theta_12, theta_13, theta_23) {
    .Call(`_idmEstimation_calc_log_likelihood`, md_ptr, theta_12, theta_13, theta_23)
}

calc_full_penalty <- function(md_ptr, theta_12, theta_13, theta_23, kappa_12, kappa_13, kappa_23) {
    .Call(`_idmEstimation_calc_full_penalty`, md_ptr, theta_12, theta_13, theta_23, kappa_12, kappa_13, kappa_23)
}

calc_penalized_log_likelihood <- function(md_ptr, theta_12, theta_13, theta_23, kappa_12, kappa_13, kappa_23) {
    .Call(`_idmEstimation_calc_penalized_log_likelihood`, md_ptr, theta_12, theta_13, theta_23, kappa_12, kappa_13, kappa_23)
}

create_pwc_model_data <- function(data) {
    .Call(`_idmEstimation_create_pwc_model_data`, data)
}

calc_log_likelihood_pwc <- function(md_ptr, lambda_12, lambda_13, lambda_23) {
    .Call(`_idmEstimation_calc_log_likelihood_pwc`, md_ptr, lambda_12, lambda_13, lambda_23)
}

